/**
 * @typedef AssetDetailsEntry
 * @property {number} assetType
 * @property {string} createdAt
 * @property {string} creatorName
 * @property {number} creatorTargetId
 * @property {string} creatorType
 * @property {string | null} description
 * @property {number} favoriteCount
 * @property {string[]} genres
 * @property {number} id
 * @property {number | null} saleCount
 * @property {boolean} isForSale
 * @property {string[]} itemRestrictions
 * @property {string} itemType
 * @property {*} lowestSellerData Extension
 * @property {string} name
 * @property {string | null} offsaleDeadline
 * @property {string} updatedAt Extension
 * @property {number|null} price Robux Price
 * @property {number} productId
 * @property {number} currency
 * @property {number|null} priceTickets
 */

// generated by ai because im NOT doing allat manually
/**
 * @typedef {Object} AvatarRules
 * @property {('R6' | 'R15')[]} playerAvatarTypes - Supported avatar types.
 * @property {Scales} scales - Scaling configuration for body parts.
 * @property {WearableAssetType[]} wearableAssetTypes - Wearable asset configuration.
 * @property {BodyColor[]} bodyColorsPalette - All available body colors.
 * @property {BodyColor[]} basicBodyColorsPalette - Subset of basic body colors.
 * @property {number} minimumDeltaEBodyColorDifference - Minimum color difference (DeltaE) for valid body color distinction.
 * @property {DefaultClothingAssetLists} defaultClothingAssetLists - Default clothing assets.
 * @property {boolean} bundlesEnabledForUser - If bundles are enabled for the user.
 * @property {boolean} emotesEnabledForUser - If emotes are enabled for the user.
 */

/**
 * @typedef {Object} ScaleRange
 * @property {number} min - Minimum value for the scale.
 * @property {number} max - Maximum value for the scale.
 * @property {number} increment - Increment step for the scale.
 */

/**
 * @typedef {Object} Scales
 * @property {ScaleRange} height
 * @property {ScaleRange} width
 * @property {ScaleRange} head
 * @property {ScaleRange} proportion
 * @property {ScaleRange} bodyType
 */

/**
 * @typedef {Object} WearableAssetType
 * @property {number} maxNumber - Maximum number of this type that can be worn.
 * @property {number} id - Unique asset type ID.
 * @property {string} name - Name of the asset type.
 */

/**
 * @typedef {Object} BodyColor
 * @property {number} brickColorId - Unique BrickColor ID.
 * @property {string} hexColor - Hexadecimal color code.
 * @property {string} name - Human-readable name of the color.
 */

/**
 * @typedef {Object} DefaultClothingAssetLists
 * @property {number[]} defaultShirtAssetIds - List of default shirt asset IDs.
 * @property {number[]} defaultPantAssetIds - List of default pants asset IDs.
 */

/**
 * @typedef {Object} RecommendedItemEntry
 * @property {RecommendedItemInternal} item - Basic information about the item.
 * @property {RecommendedItemCreator} creator - Information about the creator of the item.
 * @property {RecommendedItemProduct} product - Product-specific metadata for the item.
 */

/**
 * @typedef {Object} RecommendedItemInternal
 * @property {number} assetId - The unique identifier for the asset.
 * @property {string} name - The name of the item.
 * @property {number} price - The item's price in Robux.
 * @property {?number} premiumPrice - The price for premium users, if any.
 * @property {string} absoluteUrl - The catalog URL to the item.
 */

/**
 * @typedef {Object} RecommendedItemCreator
 * @property {number} creatorId - The ID of the creator (user or group).
 * @property {'User' | 'Group'} creatorType - The type of creator.
 * @property {string} name - The creator's display name.
 * @property {string} creatorProfileLink - Link to the creator's profile.
 */

/**
 * @typedef {Object} RecommendedItemProduct
 * @property {number} id - Product ID, usually same as asset ID.
 * @property {number?} priceInRobux - Price of the item in Robux.
 * @property {number?} priceInTickets - Price of the item in Tickets.
 * @property {boolean} isForsale - Whether the item is currently for sale.
 * @property {boolean} isPublicDomain - Whether the item is public domain.
 * @property {boolean} isResellable - Whether the item can be resold.
 * @property {boolean} isLimited - Whether the item is a limited item.
 * @property {boolean} isLimitedUnique - Whether the item is a limited unique.
 * @property {boolean} isRental - Whether the item is a rental.
 * @property {number} bcRequirement - Required Builders Club membership level (0 = none).
 * @property {number} totalPrivateSales - Total number of private sales.
 * @property {?string} offsaleDeadline - When the item will go off sale (if applicable).
 * @property {?string} noPriceText - Optional text shown when item has no price.
 * @property {number} sellerId - The seller’s user ID (0 if none).
 * @property {?string} sellerName - The name of the seller, if applicable.
 * @property {?number} lowestPrivateSaleUserAssetId - User asset ID of the lowest private sale.
 * @property {boolean} isXboxExclusiveItem - Whether the item is exclusive to Xbox.
 */

